version: '3.8'

services:
  app:
    build: .
    container_name: lazycat-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - ./logs:/app/logs
    restart: always
    networks:
      - lazycat-network

networks:
  lazycat-network:
    driver: bridge 