server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data/lazycatapp.db
  jpa:
    show-sql: true

logging:
  level:
    root: DEBUG
    xyz.mxue.lazycatapp: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    okhttp3: ERROR
  file:
    name: logs/lazycatapp-dev.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"